language: node_js
node_js:
- 6.2.0
branches:
  only:
  - master
before_script:
- npm install -g bower
- npm install -g gulp
- npm install -g firebase-tools
script:
- bower install
- gulp deploy
- ./deploy.sh
notifications:
  slack:
    secure: lM9aLW118XqJW3/r2H6ZwRPqTqrK/L5cwi4/7Zc5rc3Qf9CTfkcz5cbRILVWg7X07tna1YdsgLdkusUBZ1t0PFQQzkznrXxgyPMcuFV1jwM9DTP9wjJERyaYOVctd9JVqWyZ5ojjaPUQCCmB34XNtqDjLIRn3TAW5pCLr/RX5wYOVaiGZgSiOlIYqRvopusf+fP91zu9sJbHqzxVnLVrwWF5U9e/v85MsOj33bdsh/woL/HyfS1uHvDywVOdS6FZ8PWDsXkHq5IkmR+0jp+29Cyp3EUXG+8E0zHxxEmOD1pK7n1BnZ7FCBOICOmKHo7oyNxMzSafmxeR6seT8lNYxG2+NzTq0xDeNXsTjMi2Y8gFoe9E4bB0hcoK4DpRNFAC3ZcWH98+bO++Go+LjRl2w200txG4Oh2K0wHzDHsFiXjih7AxrO0g1C4Ybk1HyVDjr0Nj7g6uB43SBXjHHtUJVJCCN/0nX2CcF2yY6YC58lPuWXZWNYZ+hT5uoZq53Zo7iHdmj7CmaVHPKRys31Jxa4yjp8S4f3mXSEUkSEu69LBPd7OwdSlVINbWY6e19KzgxqIPJTKHoU+MOAzzDdBrI177GRPDbMVE6WkaRXp4nBSykKlQkl5BtpmY+7LXCtY+JOdhMOPdNz0eRJwRwlpjq9SN1qTY07AIv5Tw7c6trfY=